#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_Cherufe_AnimBlueprint_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3202
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3202_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3201
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3201_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3200
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3200_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4414
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4414_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4413
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4413_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3199
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3199_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3198
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3198_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4410
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4410_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_RotationOffsetBlendSpace_198
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_RotationOffsetBlendSpace_198_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4409
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4409_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3197
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3197_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3196
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3196_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4408
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4408_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4407
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4407_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3195
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3195_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3194
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3194_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3193
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3193_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ModifyBone_683
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ModifyBone_683_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3192
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3192_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3191
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3191_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3190
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3190_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_GroundBones_174
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_GroundBones_174_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_GroundBones_173
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_GroundBones_173_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ApplyAdditive_354
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ApplyAdditive_354_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3189
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3189_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3188
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3188_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4402
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4402_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3187
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3187_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3186
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3186_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3185
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3185_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4401
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4401_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4400
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4400_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3203
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3203_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3182
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3182_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ModifyBone_684
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ModifyBone_684_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3180
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3180_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4415
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_SequencePlayer_4415_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3204
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_BlendListByBool_3204_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ApplyAdditive_351
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ApplyAdditive_351_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ApplyAdditive_350
struct UCherufe_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Cherufe_AnimBlueprint_AnimGraphNode_ApplyAdditive_350_Params
{
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.BlueprintUpdateAnimation
struct UCherufe_AnimBlueprint_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Cherufe_AnimBlueprint.Cherufe_AnimBlueprint_C.ExecuteUbergraph_Cherufe_AnimBlueprint
struct UCherufe_AnimBlueprint_C_ExecuteUbergraph_Cherufe_AnimBlueprint_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
