#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_Andrewsarchus_AnimBlueprint_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.BlueprintPlayAnimationEvent
struct UAndrewsarchus_AnimBlueprint_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2874
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2874_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3871
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3871_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ModifyBone_602
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ModifyBone_602_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2873
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2873_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2872
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2872_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2871
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2871_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2870
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2870_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3870
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3870_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3869
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3869_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2869
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2869_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2868
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2868_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3865
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3865_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2867
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2867_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2866
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2866_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3864
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3864_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3863
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3863_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2865
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2865_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2864
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2864_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2863
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2863_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ModifyBone_601
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ModifyBone_601_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2862
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2862_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2861
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2861_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2860
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2860_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_GroundBones_150
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_GroundBones_150_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_GroundBones_149
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_GroundBones_149_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ApplyAdditive_280
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ApplyAdditive_280_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2859
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2859_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_RotationOffsetBlendSpace_178
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_RotationOffsetBlendSpace_178_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3858
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3858_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2858
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2858_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2857
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2857_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3857
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3857_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3856
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3856_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2856
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2856_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ApplyAdditive_279
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ApplyAdditive_279_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3855
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3855_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ApplyAdditive_278
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_ApplyAdditive_278_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3854
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_SequencePlayer_3854_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2855
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendListByBool_2855_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_204
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_204_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_203
struct UAndrewsarchus_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_203_Params
{
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.BlueprintUpdateAnimation
struct UAndrewsarchus_AnimBlueprint_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Andrewsarchus_AnimBlueprint.Andrewsarchus_AnimBlueprint_C.ExecuteUbergraph_Andrewsarchus_AnimBlueprint
struct UAndrewsarchus_AnimBlueprint_C_ExecuteUbergraph_Andrewsarchus_AnimBlueprint_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
