#pragma once

// ARKSurvivalEvolved (329.9) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransform_Archa_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransform_Archa_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6258
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6258_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7913
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7913_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ModifyBone_1074
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ModifyBone_1074_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6257
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6257_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_RotationOffsetBlendSpace_384
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_RotationOffsetBlendSpace_384_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6256
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6256_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6255
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6255_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6254
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6254_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7912
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7912_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7911
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7911_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6253
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6253_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7910
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7910_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6252
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6252_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6251
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6251_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ApplyAdditive_588
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ApplyAdditive_588_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6250
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6250_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6249
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6249_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7906
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7906_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7905
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7905_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_TwoWayBlend_120
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_TwoWayBlend_120_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6248
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6248_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7903
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7903_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6247
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6247_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6246
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6246_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7902
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7902_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7901
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7901_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6245
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6245_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7899
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7899_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6244
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6244_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6243
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6243_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6242
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6242_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7898
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7898_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7897
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_7897_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6241
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6241_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6240
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6240_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6239
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6239_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6238
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6238_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6237
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6237_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6236
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6236_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6235
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6235_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6234
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6234_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6233
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_6233_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransform_Archa_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa
struct UDinoBlueprintBase_RootTransform_Archa_C_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
