#pragma once

// ARKSurvivalEvolved (329.9) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_Mounted_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Mounted_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3294
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3294_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4649
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4649_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_696
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_696_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3293
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3293_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3292
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3292_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3291
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3291_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3290
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3290_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4648
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4648_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4647
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4647_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3289
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3289_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3288
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3288_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4644
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4644_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_RotationOffsetBlendSpace_198
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_RotationOffsetBlendSpace_198_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4643
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4643_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3287
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3287_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3286
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3286_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4642
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4642_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4641
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4641_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3285
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3285_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3284
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3284_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3283
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3283_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_695
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_695_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3282
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3282_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3281
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3281_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3280
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3280_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_186
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_186_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_185
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_185_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ApplyAdditive_342
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ApplyAdditive_342_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3279
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3279_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3278
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3278_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4636
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4636_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Mounted_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted
struct UDinoBlueprintBase_RootBoneName_Mounted_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
