#pragma once

// ARKSurvivalEvolved (320.18) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVWeaponAnimBP_Base_TekRifle_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1460
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1460_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1459
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1459_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1458
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1458_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1457
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1457_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1456
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1456_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1455
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1455_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1454
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1454_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1453
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1453_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1452
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1452_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1451
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1451_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1450
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1450_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1449
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1449_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1448
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1448_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2344
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2344_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_498
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_498_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3194
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3194_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2345
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2345_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3195
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3195_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2346
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2346_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2343
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2343_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2339
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2339_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2340
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2340_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_497
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_497_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3187
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3187_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2341
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2341_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3188
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_SequencePlayer_3188_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2342
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_BlendListByBool_2342_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_LayeredBoneBlend_114
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_LayeredBoneBlend_114_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1447
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1447_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1446
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_TransitionResult_1446_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_496
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_496_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_495
struct UFPVWeaponAnimBP_Base_TekRifle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_AnimGraphNode_ModifyBone_495_Params
{
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.BlueprintUpdateAnimation
struct UFPVWeaponAnimBP_Base_TekRifle_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base_TekRifle.FPVWeaponAnimBP_Base_TekRifle_C.ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle
struct UFPVWeaponAnimBP_Base_TekRifle_C_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekRifle_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
