#pragma once

// ARKSurvivalEvolved (329.9) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_GiantTurtle_AnimBlueprintNew_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6550
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6550_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6549
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6549_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6548
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6548_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8231
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8231_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8230
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8230_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6547
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6547_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6546
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6546_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8229
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8229_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8228
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8228_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6545
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6545_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6544
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6544_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8227
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8227_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8226
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8226_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6543
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6543_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6542
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6542_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6541
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6541_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_1097
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_1097_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6540
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6540_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6539
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6539_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6538
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6538_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_366
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_366_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_365
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_365_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ApplyAdditive_606
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ApplyAdditive_606_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6537
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6537_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8221
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8221_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6551
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6551_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6534
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6534_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6533
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6533_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_1098
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_1098_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendSpacePlayer_468
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendSpacePlayer_468_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6552
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6552_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6528
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6528_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8211
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_8211_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6527
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6527_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_RotationOffsetBlendSpace_402
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_RotationOffsetBlendSpace_402_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6525
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6525_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6524
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6524_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6523
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_6523_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.BlueprintUpdateAnimation
struct UGiantTurtle_AnimBlueprintNew_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.ExecuteUbergraph_GiantTurtle_AnimBlueprintNew
struct UGiantTurtle_AnimBlueprintNew_C_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
