#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVThrowWeaponAnimBP_Returner_Base_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3162
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3162_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3161
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3161_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3160
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3160_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3159
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3159_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3158
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3158_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3157
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3157_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3156
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3156_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3155
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3155_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3154
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3154_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3153
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3153_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3152
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3152_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3151
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3151_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3150
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3150_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3149
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3149_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3148
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3148_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3147
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_3147_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.BlueprintUpdateAnimation
struct UFPVThrowWeaponAnimBP_Returner_Base_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EnterIdle
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EnterIdle_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EnterTargetIdle
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EnterTargetIdle_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EndPullString
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EndPullString_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base
struct UFPVThrowWeaponAnimBP_Returner_Base_C_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
