#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_Ramming_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Ramming_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4122
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4122_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5231
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5231_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_804
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_804_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4121
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4121_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4120
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4120_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4119
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4119_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4118
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4118_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5230
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5230_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5229
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5229_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4117
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4117_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4116
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4116_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5226
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5226_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_RotationOffsetBlendSpace_264
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_RotationOffsetBlendSpace_264_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5225
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5225_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4115
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4115_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4114
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4114_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5224
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5224_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5223
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5223_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4113
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4113_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4112
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4112_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4111
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4111_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_803
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_803_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4110
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4110_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4109
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4109_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4108
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4108_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_252
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_252_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_251
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_251_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ApplyAdditive_444
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ApplyAdditive_444_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4107
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4107_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4106
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4106_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5218
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5218_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4105
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4105_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4104
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4104_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4103
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_4103_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5217
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5217_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5216
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_5216_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Ramming_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming
struct UDinoBlueprintBase_RootBoneName_Ramming_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
