#pragma once

// ARKSurvivalEvolved (318.14) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransformIK_Diving_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.UpdateDivingLeftRight
struct UDinoBlueprintBase_RootTransformIK_Diving_C_UpdateDivingLeftRight_Params
{
	float                                              DeltaTime;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	class ADino_Character_BP_DivingFlyer_C*            Target;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.UpdateDivingForwardBack
struct UDinoBlueprintBase_RootTransformIK_Diving_C_UpdateDivingForwardBack_Params
{
	class ADino_Character_BP_DivingFlyer_C*            Target;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransformIK_Diving_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2052
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2052_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_ModifyBone_454
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_ModifyBone_454_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2051
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2051_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_RotationOffsetBlendSpace_124
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_RotationOffsetBlendSpace_124_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2050
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2050_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2049
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2049_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2783
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2783_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2048
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2048_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2782
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2782_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2047
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2047_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2781
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2781_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2046
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2046_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2045
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2045_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2780
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2780_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2779
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2779_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2044
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2044_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2043
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2043_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2042
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2042_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2778
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2778_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2777
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2777_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2776
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2776_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendSpacePlayer_124
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendSpacePlayer_124_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2041
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2041_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2040
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2040_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendSpacePlayer_123
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendSpacePlayer_123_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2039
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2039_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2775
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2775_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_ApplyAdditive_147
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_ApplyAdditive_147_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2774
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_SequencePlayer_2774_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2038
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2038_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2037
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_BlendListByBool_2037_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_RotationOffsetBlendSpace_123
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_RotationOffsetBlendSpace_123_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_RotationOffsetBlendSpace_122
struct UDinoBlueprintBase_RootTransformIK_Diving_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_AnimGraphNode_RotationOffsetBlendSpace_122_Params
{
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransformIK_Diving_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK_Diving.DinoBlueprintBase_RootTransformIK_Diving_C.ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving
struct UDinoBlueprintBase_RootTransformIK_Diving_C_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Diving_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
