#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_MovementBlendSpace_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_MovementBlendSpace_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3648
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3648_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_702
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_702_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3647
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3647_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3646
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3646_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3645
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3645_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3644
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3644_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4545
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4545_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_RotationOffsetBlendSpace_216
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_RotationOffsetBlendSpace_216_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4544
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4544_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3643
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3643_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3642
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3642_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4543
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4543_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4542
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4542_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3641
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3641_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3640
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3640_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3639
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3639_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_701
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_701_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3638
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3638_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3637
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3637_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4540
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4540_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4539
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4539_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3636
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3636_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_216
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_216_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_215
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_215_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ApplyAdditive_300
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ApplyAdditive_300_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3635
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3635_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendSpacePlayer_174
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendSpacePlayer_174_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4537
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4537_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3634
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3634_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_MovementBlendSpace_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace
struct UDinoBlueprintBase_MovementBlendSpace_C_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
