#pragma once

// ARKSurvivalEvolved (329.9) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_Swimmer_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2226
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2226_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3273
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3273_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_ModifyBone_516
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_ModifyBone_516_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2225
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2225_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2224
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2224_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2223
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2223_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2222
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2222_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3272
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3272_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3271
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3271_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2221
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2221_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2220
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2220_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3269
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3269_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3268
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3268_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_RotationOffsetBlendSpace_142
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_RotationOffsetBlendSpace_142_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3267
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3267_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2219
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2219_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2218
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2218_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3266
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3266_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3265
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_SequencePlayer_3265_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2217
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2217_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2216
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2216_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2215
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2215_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_ModifyBone_515
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_ModifyBone_515_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2214
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2214_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2213
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2213_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2212
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2212_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_GroundBones_118
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_GroundBones_118_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_GroundBones_117
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_GroundBones_117_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_ApplyAdditive_212
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_ApplyAdditive_212_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2211
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_AnimGraphNode_BlendListByBool_2211_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Swimmer.DinoBlueprintBase_RootBoneName_Swimmer_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer
struct UDinoBlueprintBase_RootBoneName_Swimmer_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Swimmer_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
