#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVThrowWeaponAnimBP_Returner_Base_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2028
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2028_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2027
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2027_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2026
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2026_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2025
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2025_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2024
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2024_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2023
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2023_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2022
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2022_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2021
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2021_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2020
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2020_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2019
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2019_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2018
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2018_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2017
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2017_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2016
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2016_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2015
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2015_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2014
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2014_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2013
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2013_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.BlueprintUpdateAnimation
struct UFPVThrowWeaponAnimBP_Returner_Base_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EnterIdle
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EnterIdle_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EnterTargetIdle
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EnterTargetIdle_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EndPullString
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EndPullString_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base
struct UFPVThrowWeaponAnimBP_Returner_Base_C_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
