#pragma once

// ARKSurvivalEvolved (318.14) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransformIK_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransformIK_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4008
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4008_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ModifyBone_762
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ModifyBone_762_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4007
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4007_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_RotationOffsetBlendSpace_258
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_RotationOffsetBlendSpace_258_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4006
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4006_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4005
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4005_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4870
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4870_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4004
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4004_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4003
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4003_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4869
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4869_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4868
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4868_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4002
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4002_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4867
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4867_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4001
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4001_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4000
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_4000_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4865
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4865_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3999
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3999_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3998
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3998_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4864
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4864_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4863
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4863_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3997
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3997_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3996
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3996_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4862
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4862_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4861
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4861_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4860
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4860_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendSpacePlayer_192
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendSpacePlayer_192_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3994
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3994_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3993
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3993_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ApplyAdditive_342
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ApplyAdditive_342_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransformIK_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.ExecuteUbergraph_DinoBlueprintBase_RootTransformIK
struct UDinoBlueprintBase_RootTransformIK_C_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
