#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_Strafe_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Strafe_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3474
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3474_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4403
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4403_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_ModifyBone_678
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_ModifyBone_678_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3473
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3473_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3472
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3472_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3471
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3471_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3470
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3470_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4402
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4402_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4401
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4401_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3469
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3469_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3468
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3468_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4398
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4398_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_RotationOffsetBlendSpace_204
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_RotationOffsetBlendSpace_204_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4397
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4397_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3467
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3467_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3466
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3466_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4396
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4396_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4395
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_SequencePlayer_4395_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3465
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3465_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3464
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3464_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3463
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3463_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_ModifyBone_677
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_ModifyBone_677_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3462
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3462_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3461
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3461_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3460
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3460_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_GroundBones_204
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_GroundBones_204_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_GroundBones_203
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_GroundBones_203_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_ApplyAdditive_288
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_ApplyAdditive_288_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3459
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3459_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3458
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendListByBool_3458_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendSpacePlayer_168
struct UDinoBlueprintBase_RootBoneName_Strafe_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_AnimGraphNode_BlendSpacePlayer_168_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Strafe_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Strafe.DinoBlueprintBase_RootBoneName_Strafe_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe
struct UDinoBlueprintBase_RootBoneName_Strafe_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Strafe_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
