#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_GroundConform_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2250
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2250_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3071
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3071_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_ModifyBone_496
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_ModifyBone_496_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2249
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2249_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2248
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2248_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2247
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2247_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2246
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2246_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3070
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3070_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3069
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3069_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2245
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2245_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2244
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2244_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3066
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3066_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_RotationOffsetBlendSpace_144
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_RotationOffsetBlendSpace_144_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3065
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3065_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2243
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2243_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2242
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2242_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3064
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3064_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3063
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_SequencePlayer_3063_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2241
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2241_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2240
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2240_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2239
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2239_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_ModifyBone_495
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_ModifyBone_495_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2238
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2238_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2237
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2237_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2236
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2236_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_GroundBones_112
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_GroundBones_112_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_GroundBones_111
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_GroundBones_111_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_ApplyAdditive_232
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_ApplyAdditive_232_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2235
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_AnimGraphNode_BlendListByBool_2235_Params
{
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_GroundConform.DinoBlueprintBase_RootBoneName_GroundConform_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform
struct UDinoBlueprintBase_RootBoneName_GroundConform_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_GroundConform_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
