#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_GiantTurtle_AnimBlueprintNew_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4486
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4486_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4485
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4485_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4484
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4484_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5231
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5231_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5230
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5230_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4483
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4483_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4482
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4482_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5229
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5229_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5228
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5228_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4481
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4481_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4480
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4480_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5227
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5227_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5226
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5226_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4479
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4479_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4478
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4478_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4477
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4477_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_773
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_773_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4476
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4476_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4475
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4475_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4474
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4474_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_270
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_270_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_269
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_269_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ApplyAdditive_360
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ApplyAdditive_360_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4473
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4473_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5221
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5221_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4487
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4487_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4470
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4470_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4469
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4469_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_774
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_774_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendSpacePlayer_288
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendSpacePlayer_288_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4488
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4488_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4464
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4464_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5211
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5211_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4463
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4463_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_RotationOffsetBlendSpace_270
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_RotationOffsetBlendSpace_270_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4461
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4461_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4460
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4460_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4459
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4459_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.BlueprintUpdateAnimation
struct UGiantTurtle_AnimBlueprintNew_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.ExecuteUbergraph_GiantTurtle_AnimBlueprintNew
struct UGiantTurtle_AnimBlueprintNew_C_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
