#pragma once

// ARKSurvivalEvolved (329.9) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVWeaponAnimBP_Base_TekSniper_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.UpdateOverheatStatus
struct UFPVWeaponAnimBP_Base_TekSniper_C_UpdateOverheatStatus_Params
{
	class UObject*                                     Object;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2132
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2132_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2131
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2131_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2130
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2130_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2129
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2129_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2128
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2128_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2127
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2127_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2126
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2126_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2125
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2125_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2124
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2124_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2123
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2123_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2122
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2122_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2121
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2121_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2120
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2120_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2312
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2312_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_530
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_530_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3424
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3424_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2313
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2313_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3425
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3425_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2314
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2314_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2311
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2311_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2306
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2306_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2307
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2307_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_529
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_529_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3416
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3416_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2308
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2308_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3417
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3417_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2309
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2309_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_LayeredBoneBlend_118
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_LayeredBoneBlend_118_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2119
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2119_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2118
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_2118_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_528
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_528_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_527
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_527_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.BlueprintUpdateAnimation
struct UFPVWeaponAnimBP_Base_TekSniper_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper
struct UFPVWeaponAnimBP_Base_TekSniper_C_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
