#pragma once

// ARKSurvivalEvolved (320.18) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransform_Copy_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransform_Copy_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5580
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5580_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6641
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6641_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ModifyBone_864
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ModifyBone_864_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5579
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5579_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_RotationOffsetBlendSpace_330
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_RotationOffsetBlendSpace_330_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5578
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5578_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5577
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5577_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6639
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6639_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5576
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5576_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5575
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5575_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6638
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6638_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6637
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6637_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5574
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5574_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6636
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6636_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5573
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5573_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5572
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5572_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_480
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_480_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5571
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5571_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5570
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5570_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5569
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5569_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6631
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6631_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5568
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5568_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5567
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5567_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6630
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6630_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6629
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6629_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_479
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_479_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5566
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5566_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransform_Copy_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy
struct UDinoBlueprintBase_RootTransform_Copy_C_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
