#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2218
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2218_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3031
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3031_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_488
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_488_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2217
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2217_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2216
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2216_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2215
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2215_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2214
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2214_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3030
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3030_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3029
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3029_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2213
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2213_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2212
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2212_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3027
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3027_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3026
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3026_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_RotationOffsetBlendSpace_142
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_RotationOffsetBlendSpace_142_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3025
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3025_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2211
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2211_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2210
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2210_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3024
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3024_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3023
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3023_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2209
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2209_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2208
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2208_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2207
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2207_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_487
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_487_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2206
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2206_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2205
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2205_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2204
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2204_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_108
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_108_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_107
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_107_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ApplyAdditive_230
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ApplyAdditive_230_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2203
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2203_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2202
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2202_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2201
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2201_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2200
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2200_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3018
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3018_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3017
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3017_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2199
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2199_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2198
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2198_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3015
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3015_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3014
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3014_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2197
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2197_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3013
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_3013_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
