#pragma once

// ARKSurvivalEvolved (320.18) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3702
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3702_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2736
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2736_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3701
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3701_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_ModifyBone_594
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_ModifyBone_594_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2735
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2735_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2734
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2734_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2733
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2733_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2732
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2732_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3700
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3700_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3699
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3699_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2731
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2731_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2730
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2730_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3698
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3698_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3697
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3697_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3696
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3696_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_RotationOffsetBlendSpace_162
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_RotationOffsetBlendSpace_162_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3695
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3695_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2729
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2729_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2728
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2728_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3694
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3694_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3693
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3693_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2727
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2727_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2726
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2726_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3692
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3692_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2725
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2725_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_ModifyBone_593
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_ModifyBone_593_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2724
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2724_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2723
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2723_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3691
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3691_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3690
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_SequencePlayer_3690_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2722
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2722_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_GroundBones_150
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_GroundBones_150_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_GroundBones_149
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_GroundBones_149_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_ApplyAdditive_198
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_ApplyAdditive_198_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2721
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_AnimGraphNode_BlendListByBool_2721_Params
{
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_DynamicAnimOverride.DinoBlueprintBase_RootBoneName_DynamicAnimOverride_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride
struct UDinoBlueprintBase_RootBoneName_DynamicAnimOverride_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_DynamicAnimOverride_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
