#pragma once

// ARKSurvivalEvolved (320.18) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_Stego_AnimBlueprint_Impaling_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.BlueprintPlayAnimationEvent
struct UStego_AnimBlueprint_Impaling_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3558
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3558_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4496
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4496_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ModifyBone_690
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ModifyBone_690_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3557
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3557_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3556
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3556_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3555
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3555_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3554
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3554_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4495
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4495_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4494
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4494_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3553
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3553_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3552
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3552_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4491
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4491_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4490
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4490_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3551
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3551_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3550
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3550_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4489
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4489_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4488
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_SequencePlayer_4488_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3549
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3549_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3548
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3548_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3547
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3547_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ModifyBone_689
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ModifyBone_689_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ApplyAdditive_306
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ApplyAdditive_306_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3546
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3546_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3545
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_BlendListByBool_3545_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_RotationOffsetBlendSpace_210
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_RotationOffsetBlendSpace_210_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ApplyAdditive_305
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_ApplyAdditive_305_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1674
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1674_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1673
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1673_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1672
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1672_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1671
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1671_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1670
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1670_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1669
struct UStego_AnimBlueprint_Impaling_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_AnimGraphNode_TransitionResult_1669_Params
{
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.BlueprintUpdateAnimation
struct UStego_AnimBlueprint_Impaling_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Stego_AnimBlueprint_Impaling.Stego_AnimBlueprint_Impaling_C.ExecuteUbergraph_Stego_AnimBlueprint_Impaling
struct UStego_AnimBlueprint_Impaling_C_ExecuteUbergraph_Stego_AnimBlueprint_Impaling_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
