#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransform_Copy_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransform_Copy_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5346
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5346_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6401
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6401_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ModifyBone_846
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ModifyBone_846_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5345
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5345_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_RotationOffsetBlendSpace_318
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_RotationOffsetBlendSpace_318_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5344
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5344_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5343
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5343_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6399
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6399_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5342
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5342_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5341
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5341_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6398
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6398_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6397
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6397_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5340
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5340_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6396
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6396_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5339
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5339_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5338
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5338_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_450
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_450_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5337
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5337_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5336
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5336_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5335
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5335_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6391
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6391_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5334
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5334_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5333
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5333_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6390
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6390_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6389
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_6389_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_449
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_449_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5332
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_5332_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransform_Copy_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy
struct UDinoBlueprintBase_RootTransform_Copy_C_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
