#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7074
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7074_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8663
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8663_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_ModifyBone_1032
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_ModifyBone_1032_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7073
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7073_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7072
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7072_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7071
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7071_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7070
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7070_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8662
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8662_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8661
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8661_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7069
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7069_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7068
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7068_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8658
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8658_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_RotationOffsetBlendSpace_438
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_RotationOffsetBlendSpace_438_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8657
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8657_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7067
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7067_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7066
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7066_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8656
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8656_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8655
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8655_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7065
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7065_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7064
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7064_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7063
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7063_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_ModifyBone_1031
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_ModifyBone_1031_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7062
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7062_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7061
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7061_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7060
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7060_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_GroundBones_390
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_GroundBones_390_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_GroundBones_389
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_GroundBones_389_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_ApplyAdditive_654
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_ApplyAdditive_654_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7059
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7059_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7058
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7058_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8650
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_SequencePlayer_8650_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7057
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7057_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7056
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_AnimGraphNode_BlendListByBool_7056_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove.DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove
struct UDinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AllowBackwardsMove_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
