#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_MovementBlendSpace_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_MovementBlendSpace_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3816
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3816_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_768
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_768_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3815
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3815_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3814
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3814_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3813
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3813_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3812
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3812_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4959
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4959_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_RotationOffsetBlendSpace_240
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_RotationOffsetBlendSpace_240_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4958
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4958_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3811
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3811_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3810
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3810_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4957
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4957_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4956
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4956_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3809
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3809_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3808
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3808_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3807
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3807_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_767
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ModifyBone_767_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3806
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3806_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3805
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3805_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4954
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4954_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4953
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4953_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3804
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3804_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_228
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_228_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_227
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_GroundBones_227_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ApplyAdditive_420
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_ApplyAdditive_420_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3803
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3803_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendSpacePlayer_240
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendSpacePlayer_240_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4951
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_SequencePlayer_4951_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3802
struct UDinoBlueprintBase_MovementBlendSpace_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_AnimGraphNode_BlendListByBool_3802_Params
{
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_MovementBlendSpace_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_MovementBlendSpace.DinoBlueprintBase_MovementBlendSpace_C.ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace
struct UDinoBlueprintBase_MovementBlendSpace_C_ExecuteUbergraph_DinoBlueprintBase_MovementBlendSpace_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
