#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVWeaponAnimBP_Base_TekSniper_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.UpdateOverheatStatus
struct UFPVWeaponAnimBP_Base_TekSniper_C_UpdateOverheatStatus_Params
{
	class UObject*                                     Object;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1190
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1190_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1189
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1189_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1188
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1188_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1187
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1187_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1186
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1186_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1185
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1185_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1184
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1184_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1183
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1183_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1182
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1182_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1181
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1181_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1180
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1180_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1179
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1179_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1178
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1178_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2400
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2400_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_500
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_500_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3046
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3046_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2401
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2401_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3047
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3047_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2402
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2402_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2399
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2399_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2394
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2394_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2395
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2395_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_499
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_499_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3038
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3038_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2396
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2396_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3039
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3039_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2397
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2397_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_LayeredBoneBlend_116
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_LayeredBoneBlend_116_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1177
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1177_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1176
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1176_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_498
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_498_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_497
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_497_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.BlueprintUpdateAnimation
struct UFPVWeaponAnimBP_Base_TekSniper_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper
struct UFPVWeaponAnimBP_Base_TekSniper_C_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
