#pragma once

// ARKSurvivalEvolved (329.9) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVBowWeaponAnimBP_Base_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1920
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1920_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1919
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1919_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1918
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1918_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1917
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1917_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1916
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1916_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1915
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1915_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1914
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1914_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1913
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1913_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1912
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1912_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1911
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1911_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1910
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1910_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1909
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1909_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1908
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1908_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1907
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1907_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1906
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1906_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1905
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1905_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1904
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1904_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1903
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1903_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1902
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1902_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1901
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1901_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1900
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1900_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1899
struct UFPVBowWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1899_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.BlueprintUpdateAnimation
struct UFPVBowWeaponAnimBP_Base_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.AnimNotify_EnterIdle
struct UFPVBowWeaponAnimBP_Base_C_AnimNotify_EnterIdle_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.AnimNotify_EnterTargetIdle
struct UFPVBowWeaponAnimBP_Base_C_AnimNotify_EnterTargetIdle_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.AnimNotify_EndPullString
struct UFPVBowWeaponAnimBP_Base_C_AnimNotify_EndPullString_Params
{
};

// Function FPVBowWeaponAnimBP_Base.FPVBowWeaponAnimBP_Base_C.ExecuteUbergraph_FPVBowWeaponAnimBP_Base
struct UFPVBowWeaponAnimBP_Base_C_ExecuteUbergraph_FPVBowWeaponAnimBP_Base_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
