#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVWeaponAnimBP_Base_TekSniper_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.UpdateOverheatStatus
struct UFPVWeaponAnimBP_Base_TekSniper_C_UpdateOverheatStatus_Params
{
	class UObject*                                     Object;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1430
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1430_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1429
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1429_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1428
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1428_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1427
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1427_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1426
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1426_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1425
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1425_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1424
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1424_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1423
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1423_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1422
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1422_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1421
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1421_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1420
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1420_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1419
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1419_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1418
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1418_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2274
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2274_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_490
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_490_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3090
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3090_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2275
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2275_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3091
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3091_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2276
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2276_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2273
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2273_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2268
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2268_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2269
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2269_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_489
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_489_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3082
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3082_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2270
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2270_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3083
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_SequencePlayer_3083_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2271
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_BlendListByBool_2271_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_LayeredBoneBlend_112
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_LayeredBoneBlend_112_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1417
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1417_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1416
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_TransitionResult_1416_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_488
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_488_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_487
struct UFPVWeaponAnimBP_Base_TekSniper_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_AnimGraphNode_ModifyBone_487_Params
{
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.BlueprintUpdateAnimation
struct UFPVWeaponAnimBP_Base_TekSniper_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base_TekSniper.FPVWeaponAnimBP_Base_TekSniper_C.ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper
struct UFPVWeaponAnimBP_Base_TekSniper_C_ExecuteUbergraph_FPVWeaponAnimBP_Base_TekSniper_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
