#pragma once

// ARKSurvivalEvolved (320.18) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVThrowWeaponAnimBP_Returner_Base_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2064
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2064_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2063
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2063_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2062
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2062_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2061
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2061_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2060
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2060_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2059
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2059_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2058
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2058_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2057
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2057_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2056
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2056_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2055
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2055_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2054
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2054_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2053
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2053_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2052
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2052_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2051
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2051_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2050
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2050_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2049
struct UFPVThrowWeaponAnimBP_Returner_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_AnimGraphNode_TransitionResult_2049_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.BlueprintUpdateAnimation
struct UFPVThrowWeaponAnimBP_Returner_Base_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EnterIdle
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EnterIdle_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EnterTargetIdle
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EnterTargetIdle_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.AnimNotify_EndPullString
struct UFPVThrowWeaponAnimBP_Returner_Base_C_AnimNotify_EndPullString_Params
{
};

// Function FPVThrowWeaponAnimBP_Returner_Base.FPVThrowWeaponAnimBP_Returner_Base_C.ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base
struct UFPVThrowWeaponAnimBP_Returner_Base_C_ExecuteUbergraph_FPVThrowWeaponAnimBP_Returner_Base_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
