#pragma once

// ARKSurvivalEvolved (301.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransform_Archa_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransform_Archa_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5100
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5100_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6143
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6143_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ModifyBone_822
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ModifyBone_822_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5099
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5099_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_RotationOffsetBlendSpace_294
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_RotationOffsetBlendSpace_294_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5098
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5098_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5097
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5097_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5096
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5096_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6142
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6142_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6141
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6141_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5095
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5095_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6140
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6140_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5094
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5094_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5093
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5093_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ApplyAdditive_432
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ApplyAdditive_432_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5092
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5092_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5091
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5091_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6136
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6136_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6135
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6135_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_TwoWayBlend_114
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_TwoWayBlend_114_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5090
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5090_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6133
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6133_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5089
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5089_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5088
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5088_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6132
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6132_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6131
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6131_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5087
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5087_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6129
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6129_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5086
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5086_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5085
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5085_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5084
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5084_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6128
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6128_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6127
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6127_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5083
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5083_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5082
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5082_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5081
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5081_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5080
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5080_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5079
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5079_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5078
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5078_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5077
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5077_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5076
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5076_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5075
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5075_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransform_Archa_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa
struct UDinoBlueprintBase_RootTransform_Archa_C_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
