#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_FPVWeaponAnimBP_Base_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1692
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1692_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1691
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1691_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1690
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1690_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1689
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1689_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1688
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1688_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1687
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1687_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1686
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1686_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1685
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1685_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1684
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1684_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1683
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1683_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1682
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1682_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1681
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1681_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1680
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1680_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2112
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2112_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_478
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_478_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2932
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2932_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2113
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2113_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2933
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2933_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2114
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2114_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2109
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2109_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_477
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_477_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2926
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2926_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2110
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2110_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2927
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_2927_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2111
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_2111_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_LayeredBoneBlend_110
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_LayeredBoneBlend_110_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1679
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1679_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1678
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_1678_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_476
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_476_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_475
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_475_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.BlueprintUpdateAnimation
struct UFPVWeaponAnimBP_Base_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.ExecuteUbergraph_FPVWeaponAnimBP_Base
struct UFPVWeaponAnimBP_Base_C_ExecuteUbergraph_FPVWeaponAnimBP_Base_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
