#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransform_Copy_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransform_Copy_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6516
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6516_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8171
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8171_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ModifyBone_996
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ModifyBone_996_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6515
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6515_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_RotationOffsetBlendSpace_408
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_RotationOffsetBlendSpace_408_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6514
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6514_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6513
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6513_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8169
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8169_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6512
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6512_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6511
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6511_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8168
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8168_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8167
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8167_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6510
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6510_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8166
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8166_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6509
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6509_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6508
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6508_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_606
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_606_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6507
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6507_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6506
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6506_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6505
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6505_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8161
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8161_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6504
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6504_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6503
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6503_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8160
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8160_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8159
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_SequencePlayer_8159_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_605
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_ApplyAdditive_605_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6502
struct UDinoBlueprintBase_RootTransform_Copy_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_AnimGraphNode_BlendListByBool_6502_Params
{
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransform_Copy_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Copy.DinoBlueprintBase_RootTransform_Copy_C.ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy
struct UDinoBlueprintBase_RootTransform_Copy_C_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Copy_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
