#pragma once

// ARKSurvivalEvolved (318.14) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootTransform_Archa_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransform_Archa_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5184
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5184_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6239
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6239_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ModifyBone_834
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ModifyBone_834_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5183
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5183_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_RotationOffsetBlendSpace_300
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_RotationOffsetBlendSpace_300_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5182
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5182_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5181
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5181_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5180
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5180_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6238
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6238_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6237
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6237_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5179
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5179_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6236
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6236_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5178
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5178_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5177
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5177_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ApplyAdditive_450
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_ApplyAdditive_450_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5176
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5176_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5175
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5175_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6232
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6232_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6231
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6231_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_TwoWayBlend_114
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_TwoWayBlend_114_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5174
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5174_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6229
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6229_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5173
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5173_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5172
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5172_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6228
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6228_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6227
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6227_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5171
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5171_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6225
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6225_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5170
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5170_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5169
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5169_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5168
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5168_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6224
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6224_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6223
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_SequencePlayer_6223_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5167
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5167_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5166
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5166_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5165
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5165_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5164
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5164_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5163
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5163_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5162
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5162_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5161
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5161_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5160
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5160_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5159
struct UDinoBlueprintBase_RootTransform_Archa_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_AnimGraphNode_BlendListByBool_5159_Params
{
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransform_Archa_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransform_Archa.DinoBlueprintBase_RootTransform_Archa_C.ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa
struct UDinoBlueprintBase_RootTransform_Archa_C_ExecuteUbergraph_DinoBlueprintBase_RootTransform_Archa_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
