#pragma once

// ARKSurvivalEvolved (329.9) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2050
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2050_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2983
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2983_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_476
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_476_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2049
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2049_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2048
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2048_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2047
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2047_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2046
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2046_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2982
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2982_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2981
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2981_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2045
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2045_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2044
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2044_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2979
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2979_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2978
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2978_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_RotationOffsetBlendSpace_130
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_RotationOffsetBlendSpace_130_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2977
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2977_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2043
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2043_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2042
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2042_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2976
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2976_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2975
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2975_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2041
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2041_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2040
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2040_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2039
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2039_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_475
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ModifyBone_475_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2038
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2038_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2037
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2037_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2036
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2036_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_100
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_100_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_99
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_GroundBones_99_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ApplyAdditive_202
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_ApplyAdditive_202_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2035
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2035_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2034
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2034_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2033
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2033_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2032
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2032_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2970
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2970_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2969
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2969_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2031
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2031_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2030
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2030_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2967
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2967_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2966
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2966_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2029
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_BlendListByBool_2029_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2965
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_AnimGraphNode_SequencePlayer_2965_Params
{
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge.DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge
struct UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
