#pragma once

// ARKSurvivalEvolved (332.8) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARKSurvivalEvolved_IceJumperAnimBlueprint_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.BlueprintPlayAnimationEvent
struct UIceJumperAnimBlueprint_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2358
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2358_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3285
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3285_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_ModifyBone_522
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_ModifyBone_522_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2357
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2357_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2356
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2356_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2355
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2355_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3284
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3284_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3283
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3283_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2354
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2354_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2353
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2353_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3280
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3280_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2352
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2352_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2351
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2351_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3279
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3279_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3278
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3278_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2350
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2350_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2349
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2349_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2348
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2348_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_ModifyBone_521
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_ModifyBone_521_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2347
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2347_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_GroundBones_120
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_GroundBones_120_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_GroundBones_119
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_GroundBones_119_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2346
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2346_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_RotationOffsetBlendSpace_150
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_RotationOffsetBlendSpace_150_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2345
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2345_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3276
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3276_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2344
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2344_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3275
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3275_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2343
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2343_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3274
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3274_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3273
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3273_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2342
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2342_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2341
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2341_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2340
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2340_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3272
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3272_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3271
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3271_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_42
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_42_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_41
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_41_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3270
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3270_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3269
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3269_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_40
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_40_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_39
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_TwoWayBlend_39_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3268
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3268_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3267
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_SequencePlayer_3267_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2339
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_BlendListByBool_2339_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_ApplyAdditive_238
struct UIceJumperAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_IceJumperAnimBlueprint_AnimGraphNode_ApplyAdditive_238_Params
{
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.BlueprintUpdateAnimation
struct UIceJumperAnimBlueprint_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function IceJumperAnimBlueprint.IceJumperAnimBlueprint_C.ExecuteUbergraph_IceJumperAnimBlueprint
struct UIceJumperAnimBlueprint_C_ExecuteUbergraph_IceJumperAnimBlueprint_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
